version: '3.1'

services:

  tbot:
    env_file:
      - .env
    build: ./src
    ports:
      - 8080:80
    depends_on:
      - mongo


  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  flask:
    build: ./flask_server
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mongo