version: '3.1'

services:

  tbot:
    env_file:
      - .env
    build: ./src
    ports:
      - 8080:80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:81
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASS}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASS}@mongo:27017/"

  flask:
    build: ./flask_server
    ports:
      - "127.0.0.1:5000:5000"